### ISSUE TITLE
Adding User to Team not working

### ISSUE THREAD

**Issue by abhimanyuma** [spowebteam/trackr#1]
/teams/<#ID> results in an error, it is not working.

**Comment by abhimanyuma** [comment]
Referring http://stackoverflow.com/questions/5521473/rails-3-autocomplete to correct according to @shubtri

**Comment by shubtri** [comment]
Check autocomplete-2 branch, fixing it.

**Comment by abhimanyuma** [comment]
http://asciicasts.com/episodes/258-token-fields

**Comment by abhimanyuma** [comment]
This issue is closed with 1b55500a32588fac9f5b12daf34fb11722e07694 the CSS needs to be updated though
